<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Mavon.ie</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="<?php echo url('/') ?>">Home</a></li>
                <li><a href="<?php echo url('/article') ?>">Blog</a></li>
                <li><a href="">About</a></li>
            </ul>


            <?php if (isset($latest)): ?>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{{ url('/article', [$latest->getSlug()]) }}">Latest: {{ $latest->getTitle() }}</a>
                    </li>
                </ul>
            <?php endif ?>

            <div class="col-sm-3 col-md-3 pull-right">
                <form class="navbar-form" action="/search" method="get">
                    <div class="input-group">
                        <input type="text" class="form-control" value="" placeholder="Search"
                               name="term" id="term">

                        <div class="input-group-btn">
                            <button class="btn btn-default" type="submit">Search
                            </button>
                        </div>
                    </div>
                </form>
            </div>

            <?php if (\Models\User::getCurrent()): ?>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-expanded="false"><?php echo \Models\User::getCurrent()->getName() ?> <span
                                class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="<?php echo url('/admin/article') ?>">Admin</a></li>
                            <li><a href="<?php echo url('/auth/logout') ?>">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            <?php endif ?>
        </div>
    </div>
</nav>