<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Mavon.ie | <?php isset($pageTitle) ? $pageTitle : 'PHP Contractor - Ireland' ?></title>
    <link href="<?php echo elixir('css/all.css') ?>" rel="stylesheet"/>
    <!--    @yield('header')-->
</head>
<body>
    <div class="container">

        <?php $this->partial("partials/nav"); ?>

        <!--        {!! Breadcrumbs::renderIfExists() !!}-->

        <?php echo $this->flash->output(); ?>

        <!--        @include('errors.list')-->

        <div class="col-md-9">
            <?php echo $this->getContent(); ?>
        </div>
        <div class="col-md-3">
            <?php $this->partial('partials/sidebar') ?>
        </div>

        <footer>

        </footer>
    </div>
    <script src="<?php echo elixir('js/all.js') ?>"></script>
    <!--    @yield('footer')-->
</body>
</html>