<form action="/auth/start" method="post">
    <fieldset>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="text" name="email" class="form-control" placeholder="email@domain.com"/>
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" name="password" class="form-control" placeholder="Passwort"/>
        </div>
        <div>
            <button type="submit" class="btn btn-primary">Login</button>
        </div>
    </fieldset>
</form>